### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Clyde-Beep** [Jxyme/simple-discord-rpc#1]
[LOG] [3/1/2021 | 22:15:21 UTC] Attempting to connect, please wait... (if it fails, "CTRL+R" in Discord and try again)
[ERROR] [3/1/2021 | 22:15:21 UTC] (node:59832) UnhandledPromiseRejectionWarning: Error: connection closed
    at IPCTransport.<anonymous> (C:\Users\-\OneDrive\Documents\simple-discord-rpc-1.0.0\node_modules\discord-rpc\src\client.js:118:16)
    at Object.onceWrapper (events.js:421:26)
    at IPCTransport.emit (events.js:314:20)
    at C:\Users\-\OneDrive\Documents\simple-discord-rpc-1.0.0\node_modules\discord-rpc\src\transports\ipc.js:137:18
    at decode (C:\Users\-\OneDrive\Documents\simple-discord-rpc-1.0.0\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (C:\Users\-\OneDrive\Documents\simple-discord-rpc-1.0.0\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:567:12)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] [3/1/2021 | 22:15:21 UTC] (node:59832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[ERROR] [3/1/2021 | 22:15:21 UTC] (node:59832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Jxyme** [comment]
Did you happen to refresh Discord *whilst* the application was connecting? The `connection closed` error is likely caused by this.

Please can you stop/exit the application by pressing `CTRL` + `C` twice whilst the CMD/Git Bash window is in focus, and *then* refresh Discord with `CTRL` + `R` and start the application with `node .`.

If you still run into problems after following the steps above, please provide further details, and possibly steps to reproduce this issue and I will look into it.

**Comment by Clyde-Beep** [comment]
😓 I was not paying attention while editing the config and forgot to put the clientID-
Sorry for wasting your time
It works great
Again Sorry-
