### ISSUE TITLE
Optional Buttons

### ISSUE THREAD

**Issue by Matteoki** [Jxyme/simple-discord-rpc#11]
Hi there, best plugin for rich presence i've tested.

But im pretty sure the buttons are optional too, if i try to delete the json value or key the plugin refuses to work, just a little minor thing.

**Comment by Jxyme** [comment]
Hi, @Matteoki. Thank you for the feedback, I'm glad you like it!

I've just pushed an update to resolve this. Initially they weren't made to be optional.. however hopefully with these changes all should be well and good.

Please let me know if you run into any issues with these changes.

**Comment by Matteoki** [comment]
Incredible to say the least!

One more thing i found out is that the program shuts down whenever:
- Discord Crashes
- BetterDiscord Crashes
- There's no internet connection

I say this because i would like to keep the rpc on the second desktop (so that it doesn't bother me) and never touch it again (Instead of starting it again everytime it closes)

Wonderful job Jxyme!

**Comment by Jxyme** [comment]
> Incredible to say the least!
> 
> One more thing i found out is that the program shuts down whenever:
> 
> * Discord Crashes
> * BetterDiscord Crashes
> * There's no internet connection
> 
> I say this because i would like to keep the rpc on the second desktop (so that it doesn't bother me) and never touch it again (Instead of starting it again everytime it closes)
> 
> Wonderful job Jxyme!

I've just pushed an update to automatically attempt to reconnect if/when Discord closes.

Please let me know if you run into any issues with these changes.

**Comment by Matteoki** [comment]
All good!
