### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Bhavy11111** [Jxyme/simple-discord-rpc#12]
Unable to connect to Discord. Is Discord runni ng and logged-in in the background? 

Then It tries to reconnect but same error 
Pls tell how to solve it ?

**Comment by Jxyme** [comment]
There's a few reasons this can happen. Please check the following:

1. Make sure the `clientId` entered in the **config.json** is the one from the developer application found on the dashboard and __not__ your user ID.

2. If you're using the web version, it will not work. You **need** to be using the desktop application.

3. Discord needs to be running on the same exact PC. It will **not** work if you're trying to run it from a WSL, for example.

I would suggest creating a new **config.json** file from the example provided and ensure everything is correct following the steps provided.

**Comment by Bhavy11111** [comment]
@Jxyme I am doing it on mobile, I hace cloned this on replit

**Comment by Jxyme** [comment]
> @Jxyme I am trying to do it on mobile, I have cloned this on replit
> 
> 

In that case, it's not possible. As mentioned, it will only work with the desktop application on the **same** system.

Somebody else asked about this previously, you can read more here: https://github.com/Jxyme/simple-discord-rpc/issues/8 and I'll go ahead and close this issue.
