### ISSUE TITLE
RPC doesn't show up on other devices

### ISSUE THREAD

**Issue by sneazy-ibo** [Jxyme/simple-discord-rpc#15]
I used a vps tp run my status 24/7 and it worked flawless but it somehow only showup for me on my rdp and not on any other devices like my mobile although it worked before. Running it normally on my desktop still doesn't fix my issue. This is my config, I hope you can help me out.
```json
﻿{
    "clientId": "~~censored~~",
    "rich_presence": {
        "details": "𖣂 𝚜𝚗𝚎𝚊𝚣𝚢.𝚒𝚋𝚘 𐀣 ᵒᶰ ᶤᵍ ᭣݉",
        "state": "⥱ 𝚝𝚒𝚖𝚎 𝚝𝚒𝚕𝚕 𝚗𝚊𝚙 '𖥧'",
        "assets": {
            "largeImageText": "busy with school",
            "largeImageKey": "shabba",
            "smallImageText": "thighs for life ♡",
            "smallImageKey": "sheesh"
        },
        "buttons": {
            "primary": {
                "label": "𓆩 ▹ ˖𝐀𝐧𝐢𝐋𝐢𝐬𝐭.꒷꒦ 𓆪",
                "url": "https://anilist.co/user/iboxqte/"
            },
            "secondary": {
                "label": "𓆩 ▹ ˖𝐋𝐢𝐧𝐤𝐭𝐫𝐞𝐞.꒷꒦ 𓆪",
                "url": "https://linktr.ee/sneazy.ibo"
            }
        },
        "timestamps": {
            "startTimestamp": null,
            "endTimestamp": 1652824800,
            "useTimer": true
        }
    }
}
```
Btw ignore the text lol

**Comment by Jxyme** [comment]
Hmm, I can't say I've experienced anything like this before, though looking at your config it *may* be due to your primary url.

The max length is 32 and yours is exactly 32. Could you try removing the `/` on the end and restarting the RPC again?

Let me know if that resolves the issue. If it does I'll modify the validation slightly to detect this, thank you.

**Comment by sneazy-ibo** [comment]
Tysm I already thought that I can't use it on a vps anymore, but it was really just bc of the font. Do you have a Idea why the font doesn't make it visible for users but just for you?

**Comment by Jxyme** [comment]
> Tysm I already thought that I can't use it on a vps anymore, but it was really just bc of the font. Do you have a Idea why the font doesn't make it visible for users but just for you?

I logged what Discord receives and it appears to be the same, there's no errors or anything out of the ordinary with that font:

```log
[DEBUG] [18/5/2022 | 10:50:57 UTC] Primary button label: "𓆩 ▹ ˖𝐀𝐧𝐢𝐋𝐢𝐬𝐭.꒷꒦ 𓆪"
[DEBUG] [18/5/2022 | 10:50:57 UTC] Secondary button label: "𓆩 ▹ ˖𝐋𝐢𝐧𝐤𝐭𝐫𝐞𝐞.꒷꒦ 𓆪"
```

Discord successfully applies the RPC.., though unfortunately I wasn't able to figure out why it's only displaying to your client.
