### ISSUE TITLE
The buttons do not send to the link put.

### ISSUE THREAD

**Issue by InVenoxx** [Jxyme/simple-discord-rpc#2]
Place the primary button link and it doesn't send me anywhere, it doesn't do any function.

**Comment by Jxyme** [comment]
I see you didn't leave a comment after closing the issue, although I wanted to provide my input on this anyway as others may run into the same "issue" with the button(s) and come to report it.

When adding buttons to your RPC, they will function for everybody besides you. Sometimes the RPC may not display for you either, so if this happens after enabling the RPC, have a friend, server member or an alt of yours to check to ensure everything is displaying and functioning as expected.

If you have any other questions, feel free to reach out to me on Discord: Jayme#0001. :)
