### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by rockdude129** [Jxyme/simple-discord-rpc#4]
How to add a timestamp?

**Comment by Jxyme** [comment]
Set `useTimer` in **config.json** to **true**, and then provide your timestamps under `startTimestamp` and `endTimestamp`.

Also, please refer to the [Configuration Breakdown](https://github.com/Jxyme/simple-discord-rpc#configuration-breakdown) and [Presence Example](https://github.com/Jxyme/simple-discord-rpc#discord-rich-presence-example) to compare your **config.json** file with if you still struggle.

You can use [this](https://www.epochconverter.com/) website if you need help converting a specific date/time to seconds.

**Comment by rockdude129** [comment]
oh useTimer was set as false, thank you. :) you also respond very fast, very nice. :D
