### ISSUE TITLE
yall know how to run rpc client upon starting discord, as it fails on boot since discord aint up

### ISSUE THREAD

**Issue by rbrtbrnschn** [Jxyme/simple-discord-rpc#6]
im on linux.

**Comment by Jxyme** [comment]
Have you looked into possibly a Cron job with a delay to run at boot so Discord has enough time to boot before Discord-RPC attempts to connect to your client?

My experience with Linux ends with servers, I’ve never used an OS with a GUI so I’m not entirely sure what other alternatives there are to those that are on Windows. (e.g. Task Scheduler)

**Comment by lambdagg** [comment]
Maybe we could just try to implement an automatic retry every X seconds?

**Comment by omxpro** [comment]
Yes

**Comment by Jxyme** [comment]
Just released an update to address this @rbrtbrnschn. Hopefully this resolves the issue, and sorry for the delay.

The default duration to retry is set to **15** seconds, however, if you wish to shorten and/or extend this duration, you can.

Simply modify [this line](https://github.com/Jxyme/simple-discord-rpc/blob/main/index.js#L52) in **index.js** locally after downloading the latest [Release](https://github.com/Jxyme/simple-discord-rpc/releases/tag/1.0.1).

**Comment by lambdagg** [comment]
Hey @Jxyme why don't you set that in the config?

**Comment by Jxyme** [comment]
> Hey @Jxyme why don't you set that in the config?

Good question. I originally did, although I chose to remove the configuration setting before committing the changes.

I thought it would be best for the **config.json** to remain the same, primarily focused on the Discord RPC’s appearance, for ease of use purposes.

I’ve had a number of issues opened and DMs over on Discord in regards to the setup & configuration being difficult to understand, and so I personally thought this would be the right decision to make.

Hopefully you understand and can see where I’m coming from. :)

**Comment by lambdagg** [comment]
I see right. Thank you for your precious time :)
