### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by ReBlast** [Jxyme/simple-discord-rpc#9]
Hello there, I'm facing an issue with the timestamp, I don't actually know how to disable endTimestap, so the only startTimestamp would count.

**Comment by Jxyme** [comment]
> Hello there, I'm facing an issue with the timestamp, I don't actually know how to disable endTimestap, so the only startTimestamp would count.

You can use the following:

```
"timestamps": {
    "startTimestamp": "EPOCH_HERE",
    "endTimestamp": null,
    "useTimer": true
}
```

If you don't want to provide a startTimestamp and instead want it to start from the moment you start the RPC, set it to `null` as well.
